# Generated by Django 4.2.2 on 2023-06-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_createblog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
