# Generated by Django 4.2.2 on 2023-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_createblog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='author',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
